// angular-task/src/app/app.component.ts
import { Component } from '@angular/core';
import { BehaviorSubject, combineLatest, map } from 'rxjs';
import { HEADERS, Route, ROUTES } from './data';
import { ArrowComponent } from './arrow/arrow.component';
import { CommonModule } from '@angular/common';

interface Header {
  name: keyof Route;
  title: string;
  sortFn: (a: string, b: string) => number;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, ArrowComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  headers$ = new BehaviorSubject<Header[]>(HEADERS.map((h) => ({ ...h })));

  routes$ = new BehaviorSubject<Route[]>([...ROUTES]);

  lastFilter$ = new BehaviorSubject<{
    name: keyof Route | null;
    direction: 'asc' | 'desc';
    sortFn: (a: string, b: string) => number;
  }>({
    name: null,
    direction: 'asc',
    sortFn: () => 0,
  });

  sortedRoutes$ = combineLatest([
    this.headers$,
    this.routes$,
    this.lastFilter$,
  ]).pipe(
    map(([headers, routes, lastFilter]) => {
      if (!lastFilter.name) return routes;

      const headerExists = headers.find((h) => h.name === lastFilter.name);
      if (!headerExists) return routes;

      return [...routes].sort((a, b) => {
        const aValue = a[lastFilter.name!];
        const bValue = b[lastFilter.name!];
        return lastFilter.direction === 'asc'
          ? lastFilter.sortFn(aValue as string, bValue as string)
          : lastFilter.sortFn(bValue as string, aValue as string);
      });
    })
  );

  ngOnInit(): void {}

  onSort(header: Header) {
    const current = this.lastFilter$.getValue();
    const newFilter = {
      name: header.name,
      direction: current.direction,
      sortFn: header.sortFn,
    };

    if (current.name === header.name) {
      newFilter.direction = current.direction === 'asc' ? 'desc' : 'asc';
    } else {
      newFilter.direction = 'asc';
    }

    this.lastFilter$.next(newFilter);
  }

  getDirection(headerName: keyof Route): 'asc' | 'desc' | null {
    const current = this.lastFilter$.getValue();
    return current.name === headerName ? current.direction : null;
  }

  getRouteValue(route: Route, propertyName: keyof Route): string {
    return route[propertyName];
  }

  updateHeaders(newHeaders: Header[]) {
    this.headers$.next(newHeaders.map((h) => ({ ...h })));
  }

  updateRoutes(newRoutes: Route[]) {
    this.routes$.next([...newRoutes]);
  }
}

<div class="container">
  <table class="table">
    <thead class="tableHeader">
      <tr class="tableRow">
        <th *ngFor="let header of headers$ | async" (click)="onSort(header)">
          <div class="thContent">
            {{ header.title }}
            <app-arrow [direction]="getDirection(header.name)"></app-arrow>
          </div>
        </th>
      </tr>
    </thead>
    <tbody class="tableBody">
      <tr *ngFor="let route of sortedRoutes$ | async" class="tableRow">
        <td *ngFor="let header of headers$ | async">
          {{
            header.name === "address"
              ? getRouteValue(route, header.name) +
                "/" +
                getRouteValue(route, "mask")
              : getRouteValue(route, header.name)
          }}
        </td>
      </tr>
    </tbody>
  </table>
</div>

// react-task/src/App.tsx
import { HEADERS, ROUTES, type Route } from "./data";
import styles from "./App.module.css";
import { useEffect, useState } from "react";
import { Arrow } from "./ArrowIcon";

export const App = () => {
  const [routes, setRoutes] = useState<Route[]>(ROUTES);
  const [lastFilter, setLastFilter] = useState<{
    name: string;
    direction: "asc" | "desc";
    sortFn: (a: string, b: string) => number;
  }>({
    name: "",
    direction: "asc",
    sortFn: () => 0,
  });

  useEffect(() => {
    const sortedRoutes = [...routes].sort((a, b) => {
      return lastFilter.direction === "asc"
        ? lastFilter.sortFn(
            a[lastFilter.name as keyof Route],
            b[lastFilter.name as keyof Route]
          )
        : lastFilter.direction === "desc"
        ? lastFilter.sortFn(
            b[lastFilter.name as keyof Route],
            a[lastFilter.name as keyof Route]
          )
        : 0;
    });
    setRoutes(sortedRoutes);
  }, [lastFilter]);

  return (
    <div className={styles.container}>
      <table className={styles.table}>
        <thead className={styles.tableHeader}>
          <tr className={styles.tableRow}>
            {HEADERS.map((header) => (
              <th
                key={header.name}
                onClick={() => {
                  const newFilter = {
                    name: header.name,
                    direction: lastFilter.direction,
                    sortFn: header.sortFn,
                  };
                  if (lastFilter.name === header.name) {
                    newFilter.direction =
                      lastFilter.direction === "asc" ? "desc" : "asc";
                  }
                  setLastFilter(newFilter);
                }}
              >
                <div className={styles.thContent}>
                  {header.title}
                  <Arrow
                    direction={
                      lastFilter.name === header.name
                        ? lastFilter.direction
                        : null
                    }
                  />
                </div>
              </th>
            ))}
          </tr>
        </thead>
        <tbody className={styles.tableBody}>
          {routes.map((route) => (
            <tr key={route.uuid}>
              {HEADERS.map((header) => {
                const cellValue = `${route[header.name as keyof Route]}${
                  header.name === "address" ? `/${route.mask}` : ""
                }`;
                return <td key={header.name}>{cellValue}</td>;
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};
